using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using System.IO;
using System.Data.SQLite;
using System.Collections;


namespace Chilpass
{
    /*
     * Creators: Jonathan Cho and Hans Wilter
     * Chilpass_Main Partial Class
     * Summary: Contains methods for event triggers from the Chilpass_Main form.
     */

    public partial class Chilpass_Main : Form
    {

        /*
         * Constructor, initializes components.
         */
        public Chilpass_Main()
        {
            InitializeComponent();
        }

        /*
         * NewPasswordFileButton
         */
        private void NewPasswordFileButton_Click(object sender, EventArgs e)
        {
            var saveDatabaseFile = new SaveFileDialog();
            saveDatabaseFile.Filter = "Database Files (*.db) | *.db";
            saveDatabaseFile.Title = "Save a Database File";
            saveDatabaseFile.FileName = "NewPasswordFile";
            string filepath = null;

            if (saveDatabaseFile.ShowDialog() == DialogResult.OK)
            {
                filepath = saveDatabaseFile.FileName;

                FormManager.OpenNPF(filepath);
            }
        }

        /*
         * 
         */
        private void OpenPasswordFileButton_Click(object sender, EventArgs e)
        {
            var filePath = string.Empty;

            using (OpenFileDialog openFileDialog = new OpenFileDialog())
            {
                openFileDialog.InitialDirectory = "C:\\";
                openFileDialog.Filter = "Database Files (*.db) | *.db";
                openFileDialog.FilterIndex = 2;

                if (openFileDialog.ShowDialog() == DialogResult.OK)
                {
                    //Get path of file
                    filePath = openFileDialog.FileName;
                }
            }

            if (filePath != "")
            {
                string oldSalt = String.Empty;
                string oldHash = String.Empty;

                SQLiteConnection sqliteConnection;
                sqliteConnection = DatabaseManager.CreateConnection(filePath);
                oldSalt = DatabaseManager.ReadSalt(sqliteConnection);
                oldHash = DatabaseManager.ReadHash(sqliteConnection);
                sqliteConnection.Close();

                FormManager.OpenOPF(filePath, oldSalt, oldHash);
            }
        }

        /*
         * HelpButton_Click
         * Uses FormManager to open the HelpForm.
         */
        private void HelpButton_Click(object sender, EventArgs e)
        {
            FormManager.OpenHelpForm();
        }

        /*
         * ExitButton_Click
         * Closes the Chilpass_Main Form. 
         */
        private void ExitButton_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        /*
         * GeneratePasswordButton_Click
         * Uses the FormManager class to Open the GeneratePasswordForm.
         */
        private void GeneratePasswordButton_Click(object sender, EventArgs e)
        {
            FormManager.OpenGeneratePasswordForm();
        }

        /*
         * Generated by Windows Forms
         */
        private void pictureBox1_Click(object sender, EventArgs e)
        {

        }
    }
}
